apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientapp-deploy
  labels:
    app: clientapp-deploy
    tier: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clientapp-deploy
  template:
    metadata:
      labels:
        app: clientapp-deploy
    spec:
      containers:
      - name: clientapp
        image: majumi/clientapp:application
        imagePullPolicy: Always
        ports:
        - containerPort: 5100
      imagePullSecrets:
      - name: docker-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mechanicapp-deploy
  labels:
    app: mechanicapp-deploy
    tier: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mechanicapp-deploy
  template:
    metadata:
      labels:
        app: mechanicapp-deploy
    spec:
      containers:
      - name: mechanicapp
        image: majumi/mechanicapp:application
        imagePullPolicy: Always
        ports:
        - containerPort: 5200
      imagePullSecrets:
      - name: docker-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientappservice-deploy
  labels:
    app: clientappservice-deploy
    tier: appservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clientappservice-deploy
  template:
    metadata:
      labels:
        app: clientappservice-deploy
    spec:
      containers:
      - name: clientappservice
        image: majumi/clientappservice:appservice
        imagePullPolicy: Always
        ports:
        - containerPort: 5010
      imagePullSecrets:
      - name: docker-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mechanicappservice-deploy
  labels:
    app: mechanicappservice-deploy
    tier: appservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mechanicappservice-deploy
  template:
    metadata:
      labels:
        app: mechanicappservice-deploy
    spec:
      containers:
      - name: mechanicappservice
        image: majumi/mechanicappservice:appservice
        imagePullPolicy: Always
        ports:
        - containerPort: 5011
      imagePullSecrets:
      - name: docker-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carsdataservice-deploy
  labels:
    app: carsdataservice-deploy
    tier: dataservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carsdataservice-deploy
  template:
    metadata:
      labels:
        app: carsdataservice-deploy
    spec:
      containers:
      - name: carsdataservice
        image: majumi/carsdataservice:dataservice
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: docker-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientsdataservice-deploy
  labels:
    app: clientsdataservice-deploy
    tier: dataservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clientsdataservice-deploy
  template:
    metadata:
      labels:
        app: clientsdataservice-deploy
    spec:
      containers:
      - name: clientsdataservice
        image: majumi/clientsdataservice:dataservice
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
      imagePullSecrets:
      - name: docker-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mechanicsdataservice-deploy
  labels:
    app: mechanicsdataservice-deploy
    tier: dataservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mechanicsdataservice-deploy
  template:
    metadata:
      labels:
        app: mechanicsdataservice-deploy
    spec:
      containers:
      - name: mechanicsdataservice
        image: majumi/mechanicsdataservice:dataservice
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
      imagePullSecrets:
      - name: docker-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visitsdataservice-deploy
  labels:
    app: visitsdataservice-deploy
    tier: dataservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visitsdataservice-deploy
  template:
    metadata:
      labels:
        app: visitsdataservice-deploy
    spec:
      containers:
      - name: visitsdataservice
        image: majumi/visitsdataservice:dataservice
        imagePullPolicy: Always
        ports:
        - containerPort: 5003
      imagePullSecrets:
      - name: docker-secret
---
apiVersion: v1
kind: Service
metadata:
  name: clientapp
  labels:
    app: clientapp
spec:
  selector:
    app: clientapp-deploy
  type: NodePort
  ports:
  - port: 5100
    nodePort: 30101
---
apiVersion: v1
kind: Service
metadata:
  name: mechanicapp
  labels:
    app: mechanicapp
spec:
  selector:
    app: mechanicapp-deploy
  type: NodePort
  ports:
  - port: 5200
    nodePort: 30201
---
apiVersion: v1
kind: Service
metadata:
  name: clientappservice
  labels:
    app: clientappservice
spec:
  selector:
    app: clientappservice-deploy
  ports:
  - port: 5010
    targetPort: 5010
---
apiVersion: v1
kind: Service
metadata:
  name: mechanicappservice
  labels:
    app: mechanicappservice
spec:
  selector:
    app: mechanicappservice-deploy
  ports:
  - port: 5011
    targetPort: 5011
---
apiVersion: v1
kind: Service
metadata:
  name: carsdataservice
  labels:
    app: carsdataservice
spec:
  selector:
    app: carsdataservice-deploy
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: clientsdataservice
  labels:
    app: clientsdataservice
spec:
  selector:
    app: clientsdataservice-deploy
  ports:
  - port: 5001
    targetPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: mechanicsdataservice
  labels:
    app: mechanicsdataservice
spec:
  selector:
    app: mechanicsdataservice-deploy
  ports:
  - port: 5002
    targetPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: visitsdataservice
  labels:
    app: visitsdataservice
spec:
  selector:
    app: visitsdataservice-deploy
  ports:
  - port: 5003
    targetPort: 5003
